#!/bin/bash
shopt -s globstar

rm -f char2coal.zip

TEMPDIR="$(mktemp --directory --tmpdir=.)"
trap 'rm -r -f -- "$TEMPDIR"' EXIT

cp -r -T "char2coal/" "$TEMPDIR"

for fn in $TEMPDIR/**/*.json; do
    jq -c . < "$fn" > "$fn.c"
    mv -f -T "$fn.c" "$fn"
done

(
    cd "$TEMPDIR";
    zip -r -9 -D -X -q ../char2coal.zip *;
)
